#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := u8g2-demo

#COMPONENT_ADD_INCLUDEDIRS := components

include $(IDF_PATH)/make/project.mk

